baseURL = 'http://13.212.22.21/'
languageCode = 'zh-cn'
title = '我的云端博客'
theme = 'hextra'

[markup.highlight]
noClasses = false

[[menu.main]]
  name = "文章"
  pageRef = "/posts"
  weight = 1
[[menu.main]]
  name = "关于我"
  pageRef = "/about" 
  weight = 2

# 1. 开启中日韩语言支持（极其重要，否则中文搜索会搜不到！）
hasCJKLanguage = true

[params.hextra.search]
  enable = true
  flexsearch = true