baseURL = 'http://13.212.22.21/'
languageCode = 'zh-cn'
title = 'NEWTONKING'
theme = 'hextra'

# 开启中日韩语言支持
hasCJKLanguage = true

# 开启 Git 信息解析
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[[menu.main]]
  name = "文章"
  pageRef = "/posts"
  weight = 1

[[menu.main]]
  name = "关于"
  pageRef = "/about" 
  weight = 2

[[menu.main]]
  name = ""
  weight = 3
  params = { type = "search"}

# 主题全局参数配置
[params]
  displayUpdatedDate = true
  # 自定义日期格式（注意：2006年01月02日 是 Hugo 的固定占位符，请勿更改这里的数字）
  dateFormat = "2006年01月02日"

[params.search]
  enable = true
  type = "flexsearch"